
<a href="https://colab.research.google.com/github/google-research/bigbird/blob/master/bigbird/summarization/eval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2020 The BigBird Authors

Licensed under the Apache License, Version 2.0 (the "License");

In [ ]:
# Copyright 2020 The BigBird Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

In [1]:
!pip install git+https://github.com/google-research/bigbird.git -q

     |████████████████████████████████| 1.2MB 11.5MB/s 
     |████████████████████████████████| 4.3MB 50.3MB/s 
     |████████████████████████████████| 1.5MB 52.7MB/s 
     |████████████████████████████████| 3.9MB 49.5MB/s 
     |████████████████████████████████| 368kB 49.6MB/s 
     |████████████████████████████████| 655kB 46.7MB/s 
     |████████████████████████████████| 983kB 48.3MB/s 
     |████████████████████████████████| 358kB 48.5MB/s 
     |████████████████████████████████| 686kB 47.7MB/s 
     |████████████████████████████████| 194kB 56.5MB/s 
     |████████████████████████████████| 81kB 11.5MB/s 
     |████████████████████████████████| 5.6MB 42.0MB/s 
     |████████████████████████████████| 368kB 48.2MB/s 
     |████████████████████████████████| 256kB 53.2MB/s 
ERROR: kfac 0.2.3 has requirement tensorflow-probability==0.8, but you'll have tensorflow-probability 0.7.0 which is incompatible.


In [2]:
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds
import tensorflow_text as tft
from tqdm import tqdm

tf.enable_v2_behavior()

## Load Saved Model

In [3]:
path = 'gs://bigbird-transformer/summarization/pubmed/roberta/saved_model'
imported_model = tf.saved_model.load(path, tags='serve')
summerize = imported_model.signatures['serving_default']

## Setup Data

In [13]:
dataset = tfds.load('scientific_papers/pubmed', split='test', shuffle_files=False, as_supervised=True)

Dataset scientific_papers downloaded and prepared to /root/tensorflow_datasets/scientific_papers/pubmed/1.1.1. Subsequent calls will reuse this data.


In [14]:
# inspect at a few examples
for ex in dataset.take(3):
  print(ex)

(<tf.Tensor: shape=(), dtype=string, numpy=b"hypertension ( htn ) is the most common comorbidity in the world with significant public health implications     [ 1 , 2 ] . the overall u.s .\nprevalence of hypertension among adults ages 18 years in 20052008 was 30.9% and was highest among persons ages 65 years ( 69.7% )   and non - hispanic blacks ( 44% )     .  \nthe american heart association estimates that the incurred costs of hypertension are more than $ 93.5  billion per year , and that cardiovascular disease and stroke for which htn is the predominant risk factor , account for 17% of the total annual health expenditures in the united states .\nhypertension and its sequelae , heart failure ( hf ) , are a progressive disease .\nevidence shows that less than half of patients with heart failure survive five years ( after diagnosis ) , and less than a quarter of them live ten years after their initial diagnosis .\nframingham heart study showed that hypertensive patients were more likely

In [12]:
dataset

<PrefetchDataset shapes: ((), ()), types: (tf.string, tf.string)>

In [6]:
type(dataset)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

## Print predictions

In [7]:
predicted_summary = summerize(ex[0])['pred_sent'][0]

In [15]:
predicted_summary = summerize(ex[0])['pred_sent'][0]
print('Article:\n {}\n\n Predicted summary:\n {}\n\n Ground truth summary:\n {}\n\n'.format(
    ex[0].numpy(),
    predicted_summary.numpy(),
    ex[1].numpy()))

Article:
 b'\n hepatitis c virus ( hcv ) infection is reported to have a prevalence of approximately 3% worldwide .\nmajority of patients with chronic hcv have a mild , asymptomatic elevation in serum transaminase levels with no significant clinical symptoms . around 25% of patients with chronic hcv have persistently normal alanine aminotransferase ( pnalt ) .\ndefinition of normal alanine aminotransferase ( alt ) has changed over time and reference range for normal alt differs based on different laboratory cutoffs .\nprati et al .   in 2002 suggested new cutoffs with 30  u / l ( international unit ) for men and 19  u / l for women compared to 40 \nu / l and 30  u / l for men and women , respectively .\na 2009 american association for the study of liver disease ( aasld ) practice guideline suggested an alt value of 40  u / l on 2 - 3 different occasions separated by at least a month over a period of 6 months .\nothers have used 3 different alt levels equal to or below upper limit of no

In [ ]:
tmp['pred_sent'][0].numpy()

b'this article is a brief review of the british society for physiology .  \xe2\x81\x87  it includes a brief review of the british society for physiology .  \xe2\x81\x87  british japanese japanese japanese japanese japanese .  \xe2\x81\x87  british japanese japanese japanese japanese .  \xe2\x81\x87  british japanese japanese japanese japanese .  \xe2\x81\x87  japanese japanese japanese .  \xe2\x81\x87  british japanese japanese .  \xe2\x81\x87  japanese japanese .  \xe2\x81\x87  japanese japanese .'

In [ ]:
x = summerize(tf.constant('everyone at work loves lifesavers whether you crunch or suck on them all except the green and come on lifesavers bring out a grape blackberry only bag'))

{'pred_ids': <tf.Tensor: shape=(1, 256), dtype=int32, numpy=
 array([[  973, 23498,   875, 16665,   973, 23498,   875, 16665,   973,
         23498,   875, 16665,   973, 23498,   875, 16665,   973, 23498,
           875, 16665,   973, 23498,   875, 16665,   973, 23498,   875,
         16665,   973, 23498,   875, 16665,   973, 23498,   875, 16665,
           973, 23498,   875, 13987,   865,   321,   100,   973, 23498,
           875, 16665,   973, 23498,   875, 16665,   973, 23498,   875,
         16665,   973, 23498,   875, 16665,   973, 23498,   875, 16665,
           973, 23498,   875, 16665,   973, 23498,   875, 16665,   973,
         23498,   875, 13987,   865,   321,   100,   363,   973, 23498,
           875, 16665,   973, 23498,   875, 16665,   973, 23498,   875,
         16665,   973, 23498,   875, 13987,  2547,  1074,   388,   363,
           771,   387,   363,   973, 23498,   875, 16665,   973, 23498,
           875, 16665,   973, 23498,   875, 16665,  2547,  1074,   388,
   

In [16]:
def result(txt):
  x = summerize(tf.constant(txt))['pred_sent'][0].numpy()
  print(f'original: {txt} \npredicted summarization: {x}')

In [17]:
result('everyone at work loves lifesavers whether you crunch or suck on them all except the green and come on lifesavers bring out a grape blackberry only bag')

original: everyone at work loves lifesavers whether you crunch or suck on them all except the green and come on lifesavers bring out a grape blackberry only bag 
predicted summarization: b'phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotyping .  \xe2\x81\x87  phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotypic phenotyping .  \xe2\x81\x87  the phenotypic phenotypic phenotypic phenotyping method used in the work of the phenotypic phenotypic phenotypic method used in the work of the phenotypic phenotypic method used in the work of the phenotypic phenotyping method in the work of the phenotypic phenotyping method in the work of the phenotypic phenotypic method in the work of the phenotypic phenotyping method in the work of the phenotypic phenotyping method in the work of the phenotypic phenotyping method in the work of the phenotypic phenotyping method in the work of the phenotypic phenotyping method in the w

## Evaluate Rouge Scores

In [ ]:
from rouge_score import rouge_scorer
from rouge_score import scoring

In [ ]:
scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeLsum"], use_stemmer=True)
aggregator = scoring.BootstrapAggregator()

In [ ]:
for ex in tqdm(dataset.take(100), position=0):
  predicted_summary = summerize(ex[0])['pred_sent'][0]
  score = scorer.score(ex[1].numpy().decode('utf-8'), predicted_summary.numpy().decode('utf-8'))
  aggregator.add_scores(score)

100%|██████████| 100/100 [38:52<00:00, 23.32s/it]


In [ ]:
aggregator.aggregate()

{'rouge1': AggregateScore(low=Score(precision=0.0626133716965276, recall=0.09245324354755759, fmeasure=0.06909132433045363), mid=Score(precision=0.0746583443146113, recall=0.10755899354204748, fmeasure=0.08052101710380298), high=Score(precision=0.08904032679502548, recall=0.1236824852479251, fmeasure=0.0928306329324628)),
 'rouge2': AggregateScore(low=Score(precision=0.00381175250519571, recall=0.005956829545162127, fmeasure=0.00438814247007295), mid=Score(precision=0.005865650668740157, recall=0.008746112948814094, fmeasure=0.00665157835069642), high=Score(precision=0.0084917200439844, recall=0.012320302379654698, fmeasure=0.009338255444333433)),
 'rougeLsum': AggregateScore(low=Score(precision=0.05585761434091965, recall=0.0830323189114007, fmeasure=0.06221098171160909), mid=Score(precision=0.0666258100692349, recall=0.09613139230841955, fmeasure=0.07175521600863494), high=Score(precision=0.07954490388251197, recall=0.10937686014969702, fmeasure=0.08263920218454585))}

## cnn_dailymail

In [ ]:
dataset2 = tfds.load('cnn_dailymail', split='test', shuffle_files=False, as_supervised=True)

In [5]:
# inspect at a few examples
for ex in dataset2.take(3):
  print(ex)

(<tf.Tensor: shape=(), dtype=string, numpy=b"Ever noticed how plane seats appear to be getting smaller and smaller? With increasing numbers of people taking to the skies, some experts are questioning if having such packed out planes is putting passengers at risk. They say that the shrinking space on aeroplanes is not only uncomfortable - it's putting our health and safety in danger. More than squabbling over the arm rest, shrinking space on planes putting our health and safety in danger? This week, a U.S consumer advisory group set up by the Department of Transportation said at a public hearing that while the government is happy to set standards for animals flying on planes, it doesn't stipulate a minimum amount of space for humans. 'In a world where animals have more rights to space and food than humans,' said Charlie Leocha, consumer representative on the committee.\xc2\xa0'It is time that the DOT and FAA take a stand for humane treatment of passengers.' But could crowding on planes 